### ISSUE TITLE
Chat configuration via web-browser

### ISSUE THREAD

**Issue by robocobra** [DeForce/LalkaChat#169] opened 2016-11-16 14:09 UTC
Hi @DeForce I want to use your chat on Windows and Mac OS, but I don't want to install python GUI packages on my system.   It would be nice to have some kind of cross platform configuration system without having to deal with heavy packages that I will  use only to run  Your chat.

Thanks!

**Comment by DeForce** [comment] 2016-11-16 14:18
Possibly duplicate of #45 if I understand correctly.

You can run the chat without any GUI. 
I will write readme soon, please wait for that...

As for now - all configuration is stored in ./conf folder, and available to edit after you run the module (chat) first time.

If you want to disable GUI - you can do it by editing/creating file ./conf/config.cfg
and add/edit:
[gui]
gui = True # Set to false if you doesn't want GUI

**Closed** 2016-11-17 18:01 UTC
